### ISSUE TITLE
Rank 3 or 4 Betrayal Crafting Bench - Buyable?

### ISSUE THREAD

**Issue by mr-september** [CraniumViolence/craniumviolence.github.io#3]
This challenge "21 Critical Crafting" is captioned Easy - Buyable.

But we can't use other people's betrayal benches, and it can't be itemized like alvatemples.

Am I missing anything? Before I re-spec atlas nodes to get this challenge.

**Comment by CraniumViolence** [comment]
I didn't notice this, but indeed it was meant to be marked as partially buyable.
