### ISSUE TITLE
Feature requests - comment texts, and checkboxes

### ISSUE THREAD

**Issue by mr-september** [CraniumViolence/craniumviolence.github.io#4]
1. Maybe change the font style/color for your comments vs the challenges themselves. Or some kind of background box to delineate the comments vs challenges.
2. This is probably a lot harder and gonna need to implement some cookie/cache/session stuff, but it'd be incredible if there were checkboxes users could tick (and collapse/remove).

**Comment by CraniumViolence** [comment]
1. I've been intending to get around to this for a while, I'll actually bother to do something around this soon.
2. I agree, I'll look into it.

**Comment by CraniumViolence** [comment]
I'll add an option to fully hide the completed challenge labels later, I just wanted to push it as is for now.
